language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: FpylSjC5Ms7qznOzsQdnBhgzSYl9tb6FUtaYoccsPoZ8bckcCypuJyaedgQOcQMMiwyNbtvf5S2Lb8r8XrRFA4RDvrTnScK5JoM5t3Ks8gfVJC1+mmysDNwdSvB0fgbd0rzeejv/s6BFnDZ8fwr6Lw+3IF7XwQbSJCotnhFlxDKANv6dT3O/kTqLWlL7/be9zrvOV2Y0vvreLE+L/ppuD6/kyjFfHqakPHdHmRT+C9W9gftPH03QUirfFc2ivN/xrizRQSzA1jCZl6D9RecMAYxH1rFb/tcfvxmMLOYZmmbY8SsnuIbz2+sf8kw+RY17wj5awGTBDMLpf/ZglceDc/XieErIk/E1epZMOqZ6WjAUHvE2TIoJuhWE0nzIVsc7VwYvO3hzXccp48HVDVZXRdPu0Cz29lB6FEUZxsukA6/0nSb9Rh1dTZlUoZDksy/8tpcr7U5sUI+n3LRORxAiaPvA4c2Mrdsjim9YqgSRDwyghR/d5MyTt3vwJ4QbnHU7HpUmZk79aSYmwd6CDHGRZ6ifvtMTF6eUnaXIHjly9HISG1HKFv5COHAZebT+u9v6sUIQxWZFtBYITVYdgX/zNegzDfvdzUExI8PsxHxuvwgkoUnRoMpqIplN10HmB0aAW2QCHfIQ3O3KBqY00RvlbXkxTXNWYy5A+f2IvhaDYS8=
  app: ancient-savannah-32910.herokuapp.com
  on:
    repo: MarkWeigl/runners-log
